services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slavlee\CustomPackage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Slavlee\CustomPackage\Command\ExampleCommand:
    tags:
      - name: 'console.command'
        command: 'custompackage:example'
